### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by mehcode** [mehcode/linter-ui-plus#11]
[Enter steps to reproduce:]

1. Rename an open file
2. Close file

**Atom**: 1.19.0-beta3 x64
**Electron**: 1.6.9
**OS**: Mac OS X 10.12.4
**Thrown From**: [linter-ui-plus](https://github.com/mehcode/linter-ui-plus) package 0.2.1

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /Users/mehcode/.atom/packages/linter-ui-plus/lib/index.js:78

TypeError: Cannot read property 'indexOf' of undefined
    at subscriptions.add.textEditor.onDidDestroy (/packages/linter-ui-plus/index.js:78:25)
    at Function.module.exports.Emitter.simpleDispatch (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at TextEditor.module.exports.TextEditor.destroyed (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:660:26)
    at TextEditor.module.exports.Model.destroy (/Applications/Atom Beta.app/Contents/Resources/app/src/model.js:31:64)
    at Pane.module.exports.Pane.destroyItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:707:66)
    at Pane.module.exports.Pane.destroyActiveItem (/Applications/Atom Beta.app/Contents/Resources/app/src/pane.js:683:18)
    at Workspace.closeActivePaneItemOrEmptyPaneOrWindow (/Applications/Atom Beta.app/Contents/Resources/app/src/workspace.js:1703:48)
    at HTMLElement.core:close (/Applications/Atom Beta.app/Contents/Resources/app/src/register-default-commands.js:233:38)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:265:35)
    at /Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:3:65)
```

### Commands

```
     -0:30.8.0 core:backspace (input.hidden-input)
     -0:30.3.0 core:confirm (input.hidden-input)
     -0:29.1.0 core:save (input.hidden-input)
  6x -0:27.9.0 core:close (input.hidden-input)
     -0:25.9.0 core:cancel (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
     -0:21.7.0 core:save (input.hidden-input)
     -0:21.4.0 core:undo (input.hidden-input)
     -0:21.2.0 core:save (input.hidden-input)
     -0:20.2.0 core:close (input.hidden-input)
     -0:15.2.0 tree-view:rename (div.title)
     -0:14.3.0 core:move-right (input.hidden-input)
     -0:13.6.0 editor:move-to-beginning-of-word (input.hidden-input)
     -0:13.3.0 core:backspace (input.hidden-input)
     -0:12.8.0 core:confirm (input.hidden-input)
  2x -0:11.8.0 core:save (input.hidden-input)
     -0:10 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.3 
editorconfig 2.2.2 
file-type-icons 1.3.4 
flow-ide 1.6.0 
go-debug 1.5.0 
go-plus 5.5.5 
go-signature-statusbar 1.2.0 
highlight-selected 0.13.1 
hyperclick 0.1.2 
language-babel 2.66.1 
language-rust 0.4.11 
linter 2.2.0 
linter-eslint 8.2.1 
linter-ui-plus 0.2.1 
minimap-highlight-selected 4.6.1 
minimap-linter 2.0.0 
minimap-plus 4.29.2 
prettier-atom 0.36.1 
```

**Comment by mehcode** [comment]
Fixed on master

**Comment by retrixe** [comment]
Can we get a new release for this @mehcode 
Yeah, I use this package because it's great :stuck_out_tongue:

**Comment by Azakur4** [comment]
Hey @mehcode can u release a new version of this, u say u fix in master but the last release version still have this bug :( pls

thanks for this package men for me is better than the original.
